(define-module (px packages sof)
  #:use-module (gnu packages)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix build-system gnu)
  #:use-module (guix build-system trivial)
  #:use-module (gnu packages autotools)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages bison)
  #:use-module (gnu packages bootstrap)
  #:use-module (gnu packages curl)
  #:use-module (gnu packages check)
  #:use-module (gnu packages commencement)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages docbook)
  #:use-module (gnu packages documentation)
  #:use-module (gnu packages dns)
  #:use-module (gnu packages flex)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages graphviz)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages libusb)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages m4)
  #:use-module (gnu packages man)
  #:use-module (gnu packages ncurses)
  #:use-module (gnu packages networking)
  #:use-module (gnu packages cyrus-sasl)
  #:use-module (gnu packages gawk)
  #:use-module (gnu packages popt)
  #:use-module (gnu packages readline)
  #:use-module (gnu packages tls)
  #:use-module (gnu packages tex)
  #:use-module (gnu packages texinfo)
  #:use-module (gnu packages perl)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-crypto)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages security-token)
  #:use-module (gnu packages swig)
  #:use-module (gnu packages web)
  #:use-module (gnu packages xml)
  #:use-module (px packages python-xyz))

(define-public sof-bin
  (package
    (name "sof-bin")
    (version "1.5.1")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
			 (url "https://github.com/thesofproject/sof-bin")
             (commit "a06502dfe1d6d7c00fa355788430dab7527dc829")
			 (recursive? #t)))
       (sha256
        (base32 "17bl463qm01d534fld7gb4cd658y0hyzd1p3vvj7n08k8ggp8q9y"))
		(file-name (git-file-name name version))))
    (build-system trivial-build-system)
    (arguments
     `(#:modules ((guix build utils))
       #:builder (begin
                   (use-modules (guix build utils)
                                (srfi srfi-26))
                   (let* ((source     (assoc-ref %build-inputs "source"))
                          (bash       (assoc-ref %build-inputs "bash"))
                          (lib-dir    (string-append %output "/lib/firmware")))
                     (mkdir-p lib-dir)
					 (setenv "PATH" (string-append 
                                        (string-append bash       "/bin:")))
                     (copy-recursively source ".")
                     (substitute* "go.sh" (("\\$\\{ROOT\\}") %output))
                     (substitute* "go.sh" (("\\$\\{VERSION\\}") ,version))
                     (invoke "./go.sh")
					 #t))))
	(inputs `(("bash" ,bash)))
    (home-page "https://thesofproject.github.io")
    (synopsis "SOF Firmware and Topology Binaries.")
    (description
     "This is the living area and distribution channel for SOF firmware and topology binaries. It's still very much WiP and may churn a little until things settle down.")
    (license license:lgpl2.1+)))

